[package]
name = "sudoku"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bacon = "2.2.5"
clippy = "0.0.302"
rand = "0.8.5"
tabled = "0.10.0"
use = "0.0.0"

